# Generated by Django 3.1.7 on 2021-04-20 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0032_auto_20210420_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('studyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.study')),
            ],
        ),
    ]
