# Generated by Django 3.1.6 on 2021-02-09 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factors',
            fields=[
                ('factorID', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question_Text',
            fields=[
                ('questionTextID', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('questionType', models.CharField(choices=[('S5', 'Slider 0 to 5'), ('Bool', 'Boolean'), ('Short Text', 'Short Text'), ('Long Text', 'Long Text')], max_length=20)),
                ('factorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.factors')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionID', models.IntegerField(primary_key=True, serialize=False)),
                ('questionTextID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question_text')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('studyID', models.IntegerField(primary_key=True, serialize=False)),
                ('studyName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('userGroup', models.CharField(max_length=200)),
                ('studyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.study')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('questionID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='surveys.questions')),
                ('response', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='surveys.users')),
                ('streakPoints', models.IntegerField(default=0)),
                ('weeklyResponses', models.IntegerField(default=0)),
                ('totalResponses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Survey_Request',
            fields=[
                ('surveyID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('completed_p', models.BooleanField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.users')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='surveyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey_request'),
        ),
        migrations.AddField(
            model_name='factors',
            name='studyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.study'),
        ),
    ]
