# Generated by Django 3.1.6 on 2021-02-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Factors',
            new_name='Factor',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Responses',
            new_name='Response',
        ),
        migrations.RenameModel(
            old_name='Rewards',
            new_name='Reward',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
