# Generated by Django 3.1.6 on 2021-02-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20210208_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='factorName',
            field=models.CharField(default='Factor', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey_request',
            name='surveyID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
