# Generated by Django 3.1.6 on 2021-02-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20210211_2049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey_Request',
            new_name='Survey',
        ),
    ]
