# Generated by Django 3.1.6 on 2021-02-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20210215_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='expirationDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
