# Generated by Django 3.1.6 on 2021-02-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20210216_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='expirationDate',
            field=models.DateTimeField(null=True),
        ),
    ]
