# Generated by Django 3.1.6 on 2021-02-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_auto_20210217_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='token',
            field=models.CharField(default='test', max_length=6),
            preserve_default=False,
        ),
    ]
