# Generated by Django 3.1.6 on 2021-02-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_survey_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='token',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
