# Generated by Django 3.1.6 on 2021-02-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_auto_20210221_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='date',
            new_name='creationDate',
        ),
    ]
