# Generated by Django 3.1.6 on 2021-02-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_auto_20210221_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'get_latest_by': 'creationDate'},
        ),
    ]
