# Generated by Django 3.1.6 on 2021-03-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_auto_20210222_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='positive',
            field=models.BooleanField(default=True),
        ),
    ]
