# Generated by Django 3.1.6 on 2021-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_factor_positive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='positive',
        ),
        migrations.AddField(
            model_name='question_text',
            name='positive',
            field=models.BooleanField(default=True),
        ),
    ]
