# Generated by Django 3.1.6 on 2021-03-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_auto_20210301_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_text',
            old_name='positive',
            new_name='positive_p',
        ),
        migrations.AddField(
            model_name='user',
            name='active_p',
            field=models.BooleanField(default=True),
        ),
    ]
