# Generated by Django 3.1.6 on 2021-03-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_remove_user_active_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_p',
            field=models.BooleanField(default=False),
        ),
    ]
