# Generated by Django 3.1.7 on 2021-03-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_user_active_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='token',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
