# Generated by Django 3.1.7 on 2021-03-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_auto_20210314_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='removed_p',
            field=models.BooleanField(default=False),
        ),
    ]
