# Generated by Django 3.1.7 on 2021-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_survey_removed_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='removed_p',
        ),
        migrations.AddField(
            model_name='user',
            name='removed_p',
            field=models.BooleanField(default=False),
        ),
    ]
