# Generated by Django 3.1.7 on 2021-04-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_auto_20210414_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employmentTime',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
