# Generated by Django 3.1.7 on 2021-04-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0031_auto_20210416_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='contactEmail',
            field=models.EmailField(default='Contact', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='contactPerson',
            field=models.CharField(default='Contact', max_length=200),
            preserve_default=False,
        ),
    ]
