# Generated by Django 3.1.7 on 2021-04-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0033_study_feedbackurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='feedbackUrl',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
