# Generated by Django 3.1.7 on 2021-04-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_auto_20210423_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='organizationName',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
