# Generated by Django 3.1.7 on 2021-04-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0035_study_organizationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hireDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
