# Generated by Django 3.1.7 on 2021-06-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0036_auto_20210425_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
