# Generated by Django 3.1.7 on 2021-07-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0038_auto_20210717_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
